/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCalendar: typeof import('./src/components/TheCalendar.vue')['default']
    TheCAlendarioChile: typeof import('./src/components/Paises/TheCAlendarioChile.vue')['default']
    TheCAlendarioCile: typeof import('./src/components/Paises/TheCAlendarioCile.vue')['default']
    TheCAlendarioPeru: typeof import('./src/components/Paises/TheCAlendarioPeru.vue')['default']
    TheChile: typeof import('./src/components/Paises/TheChile.vue')['default']
    THeChile: typeof import('./src/components/Paises/THeChile.vue')['default']
    TheDesplegable: typeof import('./src/components/TheDesplegable.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    ThePeru: typeof import('./src/components/Paises/ThePeru.vue')['default']
  }
}
